### ISSUE TITLE
Fix LESS Imports When Running Application In Non Debug Mode

### ISSUE THREAD

**Issue by nickdibari** [Moody-Tunes/moodytunes#123]
When running the application with DEBUG set to `False`, the browse and playlists raise a 500 error on request. The full traceback is

```
ERROR: django.request - Internal Server Error: /moodytunes/browse/
Traceback (most recent call last):
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/base.py", line 263, in precompile
    mod = import_module(mod_name)
  File "/home/vagrant/mtdj_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lessc {infile} {outfile}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 131, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 107, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/base.py", line 295, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/base.py", line 235, in filter_input
    for hunk in self.hunks(forced):
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/base.py", line 205, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/base.py", line 268, in precompile
    return True, filter.input(**kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/filters/base.py", line 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/compressor/filters/base.py", line 196, in input
    raise FilterError(err)
compressor.exceptions.FilterError: FileError: '../../../../base/static/base/less/colors' wasn't found. Tried - /home/vagrant/base/static/base/less/colors.less,/home/vagrant/base/static/base/less/colors.less,../../../../base/static/base/less/colors.less in /home/vagrant/moodytunes/_static/moodytunes/less/playlist.less on line 1, column 1:
1 @import "../../../../base/static/base/less/colors";
2 
```

Looks like there's an issue with running the django_compress with debug mode off. We should investigate what's causing it and fix the issue.

Deliverables
- Browse and Playlist pages load properly

**Comment by nickdibari** [comment]
NOTE

Also update django.request logging handler to write to some file, perhaps the error logger. It wasn't evident at first what the cause of the issue was; it would have sent an email to the admins because the email handler was activated but it's nice to  have a paper trail of these exceptions.
