### ISSUE TITLE
Fix Bug In Logging Bad Request Headers

### ISSUE THREAD

**Issue by nickdibari** [Moody-Tunes/moodytunes#130]
We log all bad requests to the server to help in investigating what went wrong, as well as figure out if someone is trying to break our system. We log all request data, including request headers, when we receive a bad request. Before we log the headers, we filter out any sensitive information like sessionids or CSRF tokens. In order to preserve the original request headers and not modify them, we do a deep copy of the headers before we sanitize them for the logs. When we do try to log the headers, we get the following exception:

```
Traceback (most recent call last):
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/vagrant/mtdj_env/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vagrant/moodytunes/apps/base/mixins.py", line 112, in get
    if self._validate_request(request):
  File "/home/vagrant/moodytunes/apps/base/mixins.py", line 95, in _validate_request
    self._log_bad_request(request)
  File "/home/vagrant/moodytunes/apps/base/mixins.py", line 71, in _log_bad_request
    'params': request.GET,
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/vagrant/mtdj_env/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: cannot serialize '_io.BufferedReader' object
```

Looks like there's a problem with trying to copy a non-primitive object. The `wsgi.errors` request META key is an instance of _io.BufferedReader, which causes the deepcopy call to crash. We need to refactor this method to not blow up when trying to log the request headers.

Deliverables
- Logging statement of request headers works and does not raise an exception

**Comment by nickdibari** [comment]
NOTE

We can just log the HTTP headers for the request, filter out headers that start with `HTTP_` for the given `request.META`
