### ISSUE TITLE
Song Generator Script Mk2

### ISSUE THREAD

**Issue by nickdibari** [Moody-Tunes/moodytunes#35]
We should refactor our management command and usage of the Spotify client to be more hardened against failures and issues, right now we can't even run the script to generate songs. Looks like there's an issue with parsing the track data we get back from Spotify, should add defensive code around that segment to prevent unhandled Exceptions from being raised. We should also add some basic retry capabilities and graceful exits if exceptions are raised.

Deliverables
- Script to create songs from Spotify does not raise unhandled exceptions
- Command is engineered to gracefully handled errors

**Comment by nickdibari** [comment]
TODO

- [ ] Fix unhandled exception: retrieve `track` from each Spotify track collection safely and exit if `None` is returned

**Comment by nickdibari** [comment]
Running the command recently generated this traceback:

```python
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nick/Documents/GithubStuff/moodytunes/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/nick/Documents/GithubStuff/moodytunes/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nick/Documents/GithubStuff/moodytunes/venv/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nick/Documents/GithubStuff/moodytunes/apps/base/management/commands/__init__.py", line 46, in execute
    return super().execute(*args, **options)
  File "/home/nick/Documents/GithubStuff/moodytunes/venv/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/nick/Documents/GithubStuff/moodytunes/apps/tunes/management/commands/tunes_create_songs_from_spotify.py", line 70, in handle
    raw_tracks = spotify.get_songs_from_playlist(playlist, max_tracks_from_playlist)
  File "/home/nick/Documents/GithubStuff/moodytunes/libs/spotify.py", line 196, in get_songs_from_playlist
    uri = track['track']['uri']
TypeError: 'NoneType' object is not subscriptable
```
